name: Reusable Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure we are on the main branch
        if: ${{ inputs.branch == 'newbranch' }}  # Check if the branch is 'main'
        run: |
          echo "The workflow is running on the newbranch branch."
        
      - name: Fail if not on main branch
        if: ${{ inputs.branch != 'newbranch' }}  # If branch is not 'main', this step will fail
        run: |
          echo "This workflow can only run on the newbranch branch."
          exit 1  # Fail the job if it's not the main branch
